const ROLES = Object.freeze({
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  FACULTY: 'faculty',
  MODERATOR: 'moderator',
  STUDENT: 'student',
  PROCTOR: 'proctor',
});

const ADMIN_PERMISSIONS = Object.freeze([
  'dashboard.view',
  'assessment.view',
  'assessment.create',
  'assessment.edit',
  'assessment.review.send',
  'assessment.publish',
  'assessment.delete',
  'assessment.duplicate',
  'assessment.hide',
  'assessment.reset',
  'assessment.complete',
  'course.view',
  'course.create',
  'course.edit',
  'course.archive',
  'faculty.view',
  'faculty.view.all',
  'faculty.profile.view',
  'faculty.create',
  'faculty.edit',
  'faculty.remove',
  'moderator.view',
  'moderator.view.all',
  'moderator.profile.view',
  'moderator.create',
  'moderator.edit',
  'moderator.remove',
  'student.view',
  'student.add',
  'student.edit',
  'student.remove',
  'student.credential.regenerate',
  'proctor.add',
  'proctor.edit',
  'proctor.remove',
  'library.view',
  'library.create',
  'library.edit',
  'library.archive',
  'mail.send',
  'mail.logs.view',
  'email.template.view',
  'email.template.manage',
  'reports.view',
  'reports.score.view',
  'reports.question_analysis.view',
  'reports.process_score',
  'reports.attendance.view',
  'reports.answer_sheet.view',
  'reports.activity_log.view',
  'reports.response_log.view',
  'reports.proctoring.view',
  'reports.detail.view',
  'reports.recordings.view',
  'reports.export',
  'reports.export.csv',
  'reports.export.pdf',
  'ufm.view',
  'ufm.reverse',
  'settings.manage',
  'audit.view',
  'activity.faculty.view',
  'activity.moderator.view',
]);

const STAFF_PERMISSIONS = Object.freeze([
  'work.view',
  'assessment.questions.add',
  'assessment.questions.edit',
  'assessment.submit',
  'assessment.review',
  'library.view',
  'library.create',
  'library.edit',
  'library.archive',
]);

module.exports = {
  ROLES,
  ADMIN_PERMISSIONS,
  STAFF_PERMISSIONS,
};
