const express = require('express');
const assessmentQuestionRoutes = require('./assessmentQuestion.routes');
const assessmentProctorRoutes = require('./assessmentProctor.routes');
const assessmentRoutes = require('./assessment.routes');
const assessmentStudentRoutes = require('./assessmentStudent.routes');
const activityRoutes = require('./activity.routes');
const authRoutes = require('./auth.routes');
const courseRoutes = require('./course.routes');
const dashboardRoutes = require('./dashboard.routes');
const emailTemplateRoutes = require('./emailTemplate.routes');
const healthRoutes = require('./health.routes');
const libraryRoutes = require('./library.routes');
const peopleRoutes = require('./people.routes');
const proctorRoutes = require('./proctor.routes');
const reportRoutes = require('./report.routes');
const storageRoutes = require('./storage.routes');
const superAdminRoutes = require('./superAdmin.routes');
const studentDirectoryRoutes = require('./studentDirectory.routes');
const studentExamRoutes = require('./studentExam.routes');
const workRoutes = require('./work.routes');

const router = express.Router();

router.use('/health', healthRoutes);
router.use('/activity', activityRoutes);
router.use('/auth', authRoutes);
router.use('/courses', courseRoutes);
router.use('/assessments', assessmentRoutes);
router.use('/assessments/:assessmentId/proctors', assessmentProctorRoutes);
router.use('/assessments/:assessmentId/questions', assessmentQuestionRoutes);
router.use('/assessments/:assessmentId/students', assessmentStudentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/email-templates', emailTemplateRoutes);
router.use('/library', libraryRoutes);
router.use('/people', peopleRoutes);
router.use('/proctor', proctorRoutes);
router.use('/reports', reportRoutes);
router.use('/storage', storageRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/students', studentDirectoryRoutes);
router.use('/student', studentExamRoutes);
router.use('/work', workRoutes);

module.exports = router;
