const ASSET_BASE = '/assets/elvora-ecosystem';

export const ecosystemSteps = [
  {
    id: 'access',
    index: 1,
    label: 'ELVORA-ACCESS',
    title: 'Role-Based Workspaces',
    description: 'Dedicated dashboards for admin, faculty, moderator, proctor and student, with precise permissions for every role.',
    side: 'left',
    gridRow: 1,
    layerPosition: 10,
    zIndex: 50,
    activeImage: `${ASSET_BASE}/elvora-access-active.webp`,
    inactiveImage: `${ASSET_BASE}/elvora-access-inactive.webp`,
    width: 2400,
    height: 1610,
  },
  {
    id: 'create',
    index: 2,
    label: 'ELVORA-CREATE',
    title: 'Assessment & Question Builder',
    description: 'Create assessments, manage question banks, import content and assign academic work through one structured workspace.',
    side: 'right',
    gridRow: 2,
    layerPosition: 30,
    zIndex: 40,
    activeImage: `${ASSET_BASE}/elvora-create-active.webp`,
    inactiveImage: `${ASSET_BASE}/elvora-create-inactive.webp`,
    width: 1024,
    height: 687,
  },
  {
    id: 'collaborate',
    index: 3,
    label: 'ELVORA-COLLABORATE',
    title: 'Faculty & Moderator Workflow',
    description: 'Faculty prepare and submit assessments while moderators review, approve or return them with controlled feedback.',
    side: 'left',
    gridRow: 3,
    layerPosition: 50,
    zIndex: 30,
    activeImage: `${ASSET_BASE}/elvora-collaborate-active.webp`,
    inactiveImage: `${ASSET_BASE}/elvora-collaborate-inactive.webp`,
    width: 1024,
    height: 687,
  },
  {
    id: 'secure',
    index: 4,
    label: 'ELVORA-SECURE',
    title: 'Secure Exams & Proctoring',
    description: 'Protect every exam with password access, role controls, AI-assisted monitoring and live proctor oversight.',
    side: 'right',
    gridRow: 4,
    layerPosition: 70,
    zIndex: 20,
    activeImage: `${ASSET_BASE}/elvora-secure-active.webp`,
    inactiveImage: `${ASSET_BASE}/elvora-secure-inactive.webp`,
    width: 1024,
    height: 687,
  },
  {
    id: 'intelligence',
    index: 5,
    label: 'ELVORA-INTELLIGENCE',
    title: 'Reports & Academic Oversight',
    description: 'Track readiness, submissions, approvals, student activity and academic performance from one intelligent view.',
    side: 'left',
    gridRow: 5,
    layerPosition: 90,
    zIndex: 10,
    activeImage: `${ASSET_BASE}/elvora-intelligence-active.webp`,
    inactiveImage: `${ASSET_BASE}/elvora-intelligence-inactive.webp`,
    width: 1024,
    height: 687,
  },
];

export const ecosystemStateRanges = [
  { id: 'intro', start: 0, end: 0.09 },
  { id: 'access', start: 0.09, end: 0.25 },
  { id: 'create', start: 0.25, end: 0.41 },
  { id: 'collaborate', start: 0.41, end: 0.57 },
  { id: 'secure', start: 0.57, end: 0.73 },
  { id: 'intelligence', start: 0.73, end: 0.89 },
  { id: 'unified', start: 0.89, end: 1 },
];
